use strict;
use warnings;
use Test::More;
use File::Path qw(make_path);
use File::Spec;
use File::Temp qw(tempdir);
use FindBin;
use JSON::PP ();
use Symbol ();
use IPC::Open3 ();
use lib "$FindBin::Bin/../lib";

use PAX::CodeUnitCompiler;

=pod

=head1 NAME

t/cov_cuce_router.t - CLI router and pod-usage precompute coverage

=head1 WHY IT EXISTS

The CLI router unit builder and the build-time pod usage renderer in
C<PAX::CodeUnitCompiler> have many early-return guards and fallbacks. This file
drives each of them with synthetic router scripts in temporary directories.

=head1 DESCRIPTION

Router sources are generated by one helper with switchable defects; the
pod2usage subprocess is exercised for real and with a stubbed open3.

=cut

my $root = tempdir('pax-cov-cuce-router-XXXXXX', TMPDIR => 1, CLEANUP => 1);
my $compiler = PAX::CodeUnitCompiler->new;

# write_file($path, $text)
# Writes a fixture file, creating parent directories first.
# Input: destination path and file text. Output: the path written.
sub write_file {
    my ($path, $text) = @_;
    my ($volume, $dir) = File::Spec->splitpath($path);
    make_path($dir) if length $dir && !-d $dir;
    open my $fh, '>', $path or die "cannot write $path: $!";
    print {$fh} $text;
    close $fh or die "cannot close $path: $!";
    return $path;
}

# decode($unit)
# Decodes the JSON payload of a compiled unit record.
# Input: unit hash. Output: decoded record hash.
sub decode {
    my ($unit) = @_;
    return JSON::PP->new->decode($unit->{bytes});
}

# router_source(%opt)
# Builds a synthetic CLI router script, optionally with one defect.
# Input: option hash. Output: script source text.
sub router_source {
    my (%o) = @_;
    my $decl = $o{odd_decl} ? "my  \$cmd = shift \@ARGV||'';" : "my \$cmd = shift \@ARGV || '';";
    my $pre = $o{comment_branch} ? "if (\$cmd eq '') { }\n" : '';
    my $usage_use = $o{no_usage_use} ? '' : "use Pod::Usage qw(pod2usage);\n";
    my $text = "#!/usr/bin/perl\nuse strict;\nuse warnings;\n$usage_use";
    $text .= "use Rt::Entry;\n" if $o{use_entry};
    $text .= "$pre$decl\n";
    $text .= "my \$prelude = 1;\n" unless $o{no_prelude};
    $text .= "if (\$cmd eq '') { pod2usage(-exitval => 1, -verbose => 99, -sections => [qw(NAME SYNOPSIS)]); }\n" unless $o{no_branch};
    $text .= "if (\$cmd eq 'version') { require Rt::App; print \$" . ($o{bad_symbol} ? 'Rt::Other' : 'Rt::App') . "::VERSION, \"\\n\"; exit 0; }\n"
        unless $o{no_version};
    $text .= "if (\$cmd eq 'help') { pod2usage(-exitval => 0, -verbose => 99); }\n" unless $o{no_pod2usage};
    $text .= "print STDERR Rt::Suggest->new()->unknown_command_message(\$cmd);\n" unless $o{no_suggest} || $o{odd_suggest};
    $text .= "print STDERR Rt::Suggest->new->unknown_command_message(\$cmd);\n" if $o{odd_suggest};
    $text .= "\$ENV{RT_HOME} ||= \$0;\n" if $o{plain_env};
    $text .= "\$ENV{RT_ENTRYPOINT} ||= 'rt';\n" if $o{env_entry};
    $text .= "\nsub _prime_command_result_env { return 1 }\n" unless $o{no_prime};
    $text .= "sub _rt_entry_command { return \$ENV{RT_ENTRY} || 'rtcmd'; }\n" if $o{inline_entry};
    $text .= "1;\n\n=pod\n\n=head1 NAME\n\nrt - router test\n\n=head1 SYNOPSIS\n\n  rt [command]\n\n=cut\n";
    $text =~ s/pod2usage\(/die(/g if $o{no_pod2usage_call};
    return $text;
}

make_path("$root/proj/lib/Rt", "$root/proj/bin");
write_file("$root/proj/lib/Rt/App.pm", "package Rt::App;\nour \$VERSION = '3.14';\n1;\n");
write_file("$root/proj/lib/Rt/Entry.pm", "package Rt::Entry;\nsub _e_entry_command { return \$ENV{RT_ENTRY_ENV} || 'rtfb'; }\n1;\n");

# compile() one router source and return (unit, record).
# Input: option hash for router_source. Output: unit and decoded record.
sub build {
    my (%o) = @_;
    my $p = write_file("$root/proj/bin/rt.pl", router_source(%o));
    my $u = $compiler->compile(path => $p, kind => 'entrypoint', logical_path => $o{logical} // 'bin/rt.pl');
    return $u;
}

# The happy path with real pod2usage rendering and lazy usage import.
{
    my $u = build(use_entry => 1);
    is($u->{packaging}, 'compiled_cli_router_pcu_v1', 'router unit built');
    is($u->{logical_path}, 'bin/rt.cli-router.json', 'router logical path');
    my $r = decode($u);
    is($r->{version}, '3.14', 'router version from module roots');
    is($r->{pod_usage_lazy}, 1, 'pod usage import made lazy');
    like($r->{bootstrap_source}, qr/^sub pod2usage \{ require Pod::Usage;/, 'lazy pod2usage stub prepended');
    is($r->{usage_outputs}{help}{exit}, 0, 'help usage exit');
    like($r->{usage_outputs}{short}{stdout} . $r->{usage_outputs}{short}{stderr}, qr/router test/, 'short usage rendered from pod');
    like($r->{prelude_source}, qr/my \$prelude = 1;/, 'prelude captured before the empty-command branch');
    is($r->{subs}[0]{op}, 'app_entry_command', 'router entry sub from module');
    is($r->{subs}[0]{entrypoint_env}, 'RT_ENTRY_ENV', 'router entry env');
}

# Extension-less logical path.
is(build(logical => 'bin/rt')->{logical_path}, 'bin/rt.cli-router.json', 'router logical path without extension');

# No Pod::Usage import line, no prelude branch, no entry command at all.
{
    my $r = decode(build(no_usage_use => 1, no_branch => 1, comment_branch => 0));
    is($r->{pod_usage_lazy}, 0, 'no lazy pod usage without the import line');
    is($r->{prelude_source}, '', 'no prelude without the empty-command branch');
    is_deeply($r->{subs}, [], 'no entry subs');
}

# The empty-command branch text appears only before the declaration.
{
    my $r = decode(build(no_branch => 1, comment_branch => 1));
    is($r->{prelude_source}, '', 'branch before declaration yields no prelude');
}

# Entry command discovered by plain env assignment capture and inline sub.
{
    my $r = decode(build(env_entry => 1));
    is($r->{subs}[0]{entrypoint_env}, 'RT_ENTRYPOINT', 'entry from ENTRYPOINT env assignment');
    my $r2 = decode(build(plain_env => 1, inline_entry => 1));
    is($r2->{subs}[0]{name}, '_rt_entry_command', 'entry captured via generic assignment keeps symbolic name');
    my $r3 = decode(build(plain_env => 1, logical => 'bin/rt'));
    is($r3->{subs}[0]{entrypoint_fallback}, 'rt', 'entry fallback derived from logical path');
}

# Sub-name fallbacks when the entry lookup yields no symbolic name.
{
    no warnings 'redefine';
    my $p = write_file("$root/proj/bin/rt.pl", router_source(inline_entry => 1));
    local *PAX::CodeUnitCompiler::_entry_command_from_entrypoint = sub { return { env => 'E', fallback => 'f' } };
    my $r = decode($compiler->compile(path => $p, kind => 'entrypoint', logical_path => 'bin/rt.pl'));
    is($r->{subs}[0]{name}, '_rt_entry_command', 'entry sub name from source');
    my $p2 = write_file("$root/proj/bin/rt.pl", router_source());
    my $r2 = decode($compiler->compile(path => $p2, kind => 'entrypoint', logical_path => 'bin/rt.pl'));
    is($r2->{subs}[0]{name}, 'entrypoint', 'entry sub default name');
}

# Each guard rejects the source (router falls through to a plain script unit).
for my $defect (qw(odd_decl odd_suggest no_version no_pod2usage_call no_suggest no_prime bad_symbol)) {
    my $p = write_file("$root/proj/bin/rt.pl", router_source($defect eq 'no_pod2usage_call' ? (no_pod2usage => 1, no_pod2usage_call => 1) : ($defect => 1)));
    my $src = router_source($defect eq 'no_pod2usage_call' ? (no_pod2usage => 1, no_pod2usage_call => 1) : ($defect => 1));
    if ($defect eq 'no_pod2usage_call') {
        $src =~ s/pod2usage//g;
        $p = write_file("$root/proj/bin/rt.pl", $src);
    }
    my $u = $compiler->compile(path => $p, kind => 'entrypoint', logical_path => 'bin/rt.pl');
    isnt($u->{packaging}, 'compiled_cli_router_pcu_v1', "router guard rejects: $defect");
}
is(PAX::CodeUnitCompiler::_compiled_cli_router_unit('/x', 'entrypoint', 'x', 'print 1;'), undef, 'router: missing cmd declaration');

# Router without any pod2usage use never spawns a subprocess.
is(PAX::CodeUnitCompiler::_precompute_pod_usage('/x', 'print 1;'), undef, 'pod usage: not used');

# pod usage failure modes with stubbed open3.
{
    no warnings 'redefine';
    my $p = write_file("$root/proj/bin/pod.pl", "use Pod::Usage;\npod2usage();\n\n=pod\n\n=head1 NAME\n\nx - y\n\n=cut\n");
    {
        local *IPC::Open3::open3 = sub { die "no fork\n" };
        is(PAX::CodeUnitCompiler::_precompute_pod_usage($p, 'pod2usage();'), undef, 'pod usage: open3 failure');
    }
    {
        local *IPC::Open3::open3 = sub {
            open $_[0], '>', File::Spec->devnull or die;
            $_[1] = Symbol::gensym();
            $_[2] = Symbol::gensym();
            return -1;
        };
        local $SIG{__WARN__} = sub { };
        my $out = PAX::CodeUnitCompiler::_precompute_pod_usage($p, 'pod2usage();');
        is($out->{help}{stdout}, '', 'pod usage: undefined stdout becomes empty');
        is($out->{help}{stderr}, '', 'pod usage: undefined stderr becomes empty');
    }
    {
        local *IPC::Open3::open3 = sub { return 0 };
        is(PAX::CodeUnitCompiler::_precompute_pod_usage($p, 'pod2usage();'), undef, 'pod usage: false pid');
    }
    my $real = PAX::CodeUnitCompiler::_precompute_pod_usage($p, 'pod2usage();');
    is($real->{help}{exit}, 0, 'pod usage: real help render');
    is($real->{short}{exit}, 1, 'pod usage: real short render');
}

# Router with a usage-output failure keeps the source pod2usage import.
{
    no warnings 'redefine';
    local *PAX::CodeUnitCompiler::_precompute_pod_usage = sub { return undef };
    my $p = write_file("$root/proj/bin/rt.pl", router_source());
    my $r = decode($compiler->compile(path => $p, kind => 'entrypoint', logical_path => 'bin/rt.pl'));
    is($r->{pod_usage_lazy}, 0, 'pod usage not lazy when precompute fails');
    ok(!exists $r->{usage_outputs}, 'no usage_outputs when precompute fails');
}

done_testing;
